Plugin system restyling
NeroReflex/Pizza pull request #15
Opened 2016-09-13 13:48 UTC by NeroReflex

Cambiamenti __STRUTTURALI__:
- i plugin tornano a NON avere tipo, quindi un plugin unisce entrambe le tipologie.
- il parsing del messaggio va fatto a mano (anche se il vecchio parsing rimane disponibile per retro-compatibilità e perché può far comodo ai neofiti)
- ogni plugin lancia ben DUE Threads (per evitare che i due meccanismi di plugin si limitino fra loro)
- le funzioni si lanciano così:
!convert hex2bin 1aff5
- una facile ed intuitiva guida si invoca così: !help
- la guida di uno specifico plugin si invoca così: !help convert
- maggiore velocità a runtime, soprattutto nel main thread (parte critica in Pizza)

2016-09-13 14:32 UTC, doppioandante commented on src/main/java/com/neroreflex/pizza/Pizza.java
> +                this.enqueueMessage(new Message(channel, "I don't know what I have to do at '" + command + "' request :("));
Nel caso il comando non esista secondo me è più chiaro non scrivere nulla.

2016-09-13 14:33 UTC, doppioandante commented on src/main/java/com/neroreflex/pizza/Pizza.java
> +            this.enqueueMessage(new Message(channel, "Sono il vostro amichevole robottino mangiapizza :)"));
Sincramente toglierei questo messaggio, a parte che non fa simpatia è pure in Italiano mentre gli altri sono in Inglese.

2016-09-13 14:35 UTC, doppioandante commented on src/main/java/com/neroreflex/pizza/Pizza.java
> +        } // Devo stampare SOLO l'help del plugin richiesto
I commenti come questo sono un po' lapalissiani, mi pare che il codice si capisca bene anche senza.

2016-09-13 14:36 UTC, doppioandante commented on src/main/java/com/neroreflex/pizza/Pizza.java
> +                this.enqueueMessage(new Message(helpRequest.GetChannel(), "A plugin named '" + name + "' doesn't exist."));
No plugin named 'name' exists

2016-09-13 14:36 UTC, doppioandante commented on src/main/java/com/neroreflex/pizza/Pizza.java
> +                    this.enqueueMessage(new Message(helpRequest.GetChannel(), "Usage help is not bundled with the '" + name + "' plugin."));
Help e basta invece di Usage help

2016-09-13 14:38 UTC, doppioandante commented on src/main/java/com/neroreflex/pizza/Request.java
> +            if (params[i].length() > 0) args.add(params[i]);
Non dovrebbe essere impossibile che i capture abbiano lunghezza nulla?

2016-09-13 14:39 UTC, doppioandante commented on src/main/java/com/neroreflex/pizza/Trancio.java
> +    protected void onInitialize() {}
Perché non sono abstract?

2016-09-13 14:47 UTC, doppioandante commented
Ci ho dato uno sguardo molto veloce, una cosa che mi preme è che con @gianluca-nitti avevamo fatto in modo che il bot di hackernews andasse a intervalli regolari ma a partire da ore prestabilità, cosa che si è persa quando hai messo l'autotrancio.
Non ho ancora guardato cosa intendi per 'ogni plugin lancia ben DUE Threads' ma a sentirla così non sembra una grande cosa, guarderò meglio se avrò tempo.

2016-09-13 15:11 UTC, NeroReflex commented on src/main/java/com/neroreflex/pizza/Pizza.java
> +                this.enqueueMessage(new Message(channel, "I don't know what I have to do at '" + command + "' request :("));
!time
dopo un ipotetico secondo.....
ma è morto o il plugin non esiste?

2016-09-13 15:13 UTC, NeroReflex commented on src/main/java/com/neroreflex/pizza/Request.java
> +            if (params[i].length() > 0) args.add(params[i]);
Secondo i test condotti da me e GN direi proprio di no (purtroppo)!

2016-09-13 15:14 UTC, NeroReflex commented on src/main/java/com/neroreflex/pizza/Trancio.java
> +    protected void onInitialize() {}
se fossero abstract saresti costretto a definirli. E' abstract la classe, può bastare.

2016-09-13 15:14 UTC, doppioandante commented on src/main/java/com/neroreflex/pizza/Pizza.java
> +                this.enqueueMessage(new Message(channel, "I don't know what I have to do at '" + command + "' request :("));
!help dà la risposta

2016-09-13 18:47 UTC, NeroReflex commented on src/main/java/com/neroreflex/pizza/Pizza.java
> +                this.enqueueMessage(new Message(channel, "I don't know what I have to do at '" + command + "' request :("));
Non lo so.... Mi sembra brutto (e un po' maleducato)....

2016-09-13 20:39 UTC, NeroReflex commented on src/main/java/com/neroreflex/pizza/Pizza.java
> +            this.enqueueMessage(new Message(channel, "Sono il vostro amichevole robottino mangiapizza :)"));
Per questo mi piace :D

2016-09-19 21:09 UTC, gianluca-nitti commented
@NeroReflex @doppioandante c'è qualche motivo particolare per cui non è ancora stato fatto il merge in master?

2016-09-19 22:43 UTC, doppioandante commented
Perché @NeroReflex aveva trovato un problema che adesso non ricordo.
A me sinceramente non piace il discorso dei due thread, dovrebbero essercene due solo se il plugin richiede l'attivazione periodica.
E comunque ancora non mi convince del tutto che ci sia questo kitchen sink dentro il plugin, preferivo una soluzione come quella dell'autotrancio che aggiunge la funzionalità del polling estendendo la classe Trancio: prima l'architettura del tutto rendeva le due cose esclusive, ora invece si può benissimo implementare così.

Un'altra cosa che non ho capito a che scopo sia stata messa è DelayedRequest.

A parte questo non ho molto altro in contrario. In futuro mi piacerebbe che Request e Message venissero unificati perché non ha senso avere una distinzione semantica riguardo alla provenienza, è già implicita nella gerarchia di comunicazione bot/plugin.

2016-09-21 20:23 UTC, doppioandante commented on src/main/java/com/neroreflex/pizza/Pizza.java
> +        if ((message.charAt(0) == '!') && (message.length() > 1)) {
Può essere che arrivi un messaggio di lunghezza nulla?

2016-09-21 20:24 UTC, doppioandante commented on src/main/java/com/neroreflex/pizza/Pizza.java
> +            firstSpacePos = (firstSpacePos <= -1)? message.length() : firstSpacePos;
Nit: di solito ci va lo spazio prima del ? del ternario, ma lascia pure così.

2016-09-21 20:26 UTC, doppioandante commented on src/main/java/com/neroreflex/pizza/Pizza.java
> +                this.enqueueMessage(new Message(channel, "I don't know what I have to do at '" + command + "' request :("));
La grammatica corretta sarebbe "to do with", e probabilmente quel "request" alla fine va tolto.

2016-09-21 20:27 UTC, doppioandante commented on src/main/java/com/neroreflex/pizza/Pizza.java
> +        }
Penso che sarebbe più semplice far stampare semplicemente I'm blabla + url github (com'era prima forse?), è una complicazione inutile avere dei subcommands per info.

2016-09-21 20:30 UTC, doppioandante commented on src/main/java/com/neroreflex/pizza/Pizza.java
> +                            this.enqueueMessage(new Message(helpRequest.GetChannel(), "!" + name + " " + help));
Per ora OK, ma il si dovrà cambiare in modo che il messaggio con le informazioni di help arrivi in privato all'utente che l'ha richiesto, altrimenti intasa la chat (specie con molti plugin o con help lunghi).

2016-09-21 20:30 UTC, doppioandante commented on src/main/java/com/neroreflex/pizza/Pizza.java
> +                    this.enqueueMessage(new Message(helpRequest.GetChannel(), "Help is not bundled with the '" + name + "' plugin."));
(There's) No help is provided by <name>

2016-09-21 20:50 UTC, doppioandante commented on src/main/java/com/neroreflex/pizza/Trancio.java
> +    };
RequestRunner e TimerRunner si potevano fare come classi anonime ma va bene anche così.

2016-09-21 20:52 UTC, doppioandante commented on src/main/java/com/neroreflex/plugins/Join.java
> +            this.sendMessage(new Message(channel, user + " Invalid channel name"));
Questo else avviene quando non si dà nessun canale, quindi ha più senso il messaggio che c'era prima.

2016-09-21 20:53 UTC, doppioandante commented on src/main/java/com/neroreflex/plugins/Join.java
> +            this.sendMessage(new Message(channel, user + " I have joined the " + newChannel + " channel"));
Il messaggio di prima era meno verboso e si capisce ugualmente per via del # prima del nome del canale.

2016-09-21 20:53 UTC, doppioandante requested changes

2016-09-21 21:11 UTC, NeroReflex commented on src/main/java/com/neroreflex/pizza/Pizza.java
> +        if ((message.charAt(0) == '!') && (message.length() > 1)) {
https://tools.ietf.org/html/rfc2812.html Sezione 2.3.1: "Empty messages are silently ignored"

2016-09-21 21:21 UTC, doppioandante approved these changes

2016-09-21 21:54 UTC, doppioandante approved these changes

2016-09-21 22:23 UTC, merged