Remove everything except the build artifact in the docker image
NeroReflex/Pizza pull request #20
Opened 2017-08-07 23:16 UTC by doppioandante

2017-08-08 08:49 UTC, NeroReflex commented
Mi sembra una ottima idea. L'hai provata? Quanto spazio si risparmia?

2017-08-08 08:50 UTC, NeroReflex requested changes
Mi sembra una ottima idea. L'hai provata? Quanto spazio si risparmia?

2017-08-08 08:50 UTC, NeroReflex reviewed
Mi sembra una ottima idea. L'hai provata? Quanto spazio si risparmia?

2017-08-08 08:53 UTC, NeroReflex approved these changes

2017-08-08 19:57 UTC, doppioandante commented
Purtroppo la maggior parte dello spazio della cartella target la occupa lib/ con tutte le dipendenze, sta sui 38MB.
Quindi risparmiamo solo qualche mega, meglio di nulla..

2017-08-09 13:12 UTC, NeroReflex commented
Beh se funziona non ho problemi ad approvare...

2017-08-14 19:10 UTC, doppioandante commented
Alla fine ho deciso che la fragilità aggiunta al dockerfile non vale la pena per pochi MB, quindi per ora chiudo.
Il fatto che il bot sia sui 40MB è abbastanza preoccupante, dovremmo vedere se per caso non ci sono dipendenze inutili che ci stiamo tirando dietro.

2017-08-14 19:10 UTC, closed without merging