Redesign
NeroReflex/Pizza pull request #21
Opened 2017-08-09 13:13 UTC by NeroReflex

I plugin possono catturare gli eventi.

2017-08-09 19:45 UTC, NeroReflex commented
Queste modifiche sono molto importanti e riguardano il modo nei quali i plugin vengono chiamati a comportarsi:
  - ho aggiunto delle funzioni che i plugin possono implementare per catturare gli eventi (onUserEnterChanel, onUserLeaveChanel ecc..)
  - ho cambiato la firma della funzione onCall il cui utilizzo adesso è più immediato
  - la classe Request (che attivava il metodo onCall con l'ausilio di una coda bloccante) adesso e' diventata la classe Event, che rappresenta un evento al quale ogni plugin deve rispondere
  - ogni tipo di evento (enum EventType) ha la sua classe corrispondente
  - ogni evento viene inviato a tutti i plugin ad eccezione di quello che chiama un singolo plugin all'esecuzione (!calc 3 + 1 è inviato solo al plugin calc)
  - ho modificato la documentazione in accordo ai cambiamenti
  - la classe Trancio (quella base dei plugin) contiene un metodo chiamato "processEvent" che si occupa di chiamare il giusto event handler ad ogni evento ricevuto.
  - onHelp è ora una funzione void che viene eseguita sul thread del plugin, per scongiurare effetti indesiderati e dare maggiore stabilità al thread primario
  - spostato il saluto in un plugin che si occupa di salutare i nuovi utenti

2017-08-14 19:07 UTC, doppioandante requested changes
In generale OK l'interfaccia pubblica di Trancio, invece non mi convince la struttura delle classi Event perché avere EventType e anche il subclassing va contro l'open/closed principle (e tuttavia in questo caso non vogliamo che la classe Event sia estendibile se non da noi).

2017-08-14 19:07 UTC, doppioandante commented on src/main/java/com/neroreflex/pizza/Pizza.java
> + * La classe che, una volta istanziata identifichera' un bot connesso ad un server
Perché hai tolto l'accento? I sorgenti sono codificati in UTF-8 non c'è nessun problema.

2017-08-14 19:07 UTC, doppioandante commented on Documentazione/docs/plugin.md
> +  - protected void onShutdown(...): metodo chiamato nel main thread, al momento della attivazione del plugin, quindi _*PERICOLOSO*_
Cosa vuol dire tecnicamente pericoloso?

2017-08-14 19:07 UTC, doppioandante commented on src/main/java/com/neroreflex/plugins/Hello.java
> +        if (this.getName().compareTo(sender) != 0)
Usa equals

2017-08-14 19:07 UTC, doppioandante commented on src/main/java/com/neroreflex/pizza/Trancio.java
> +     * La coda di eventi che il plugin dovra' risolvere.
risolvere -> gestire

2017-08-14 19:07 UTC, doppioandante commented on src/main/java/com/neroreflex/pizza/Trancio.java
> +     * Se unqueueEvent ed enqueueEvent dovessero essere entrambi synchronized
dovessero

2017-08-14 19:07 UTC, doppioandante commented on src/main/java/com/neroreflex/pizza/Trancio.java
> +    protected void onUserLeaveChanel(String channel, String sender, String login, String hostname) {}
onUserLeaveChannel

2017-08-14 19:07 UTC, doppioandante commented on src/main/java/com/neroreflex/pizza/Trancio.java
> +    protected void onUserEnterChanel(String channel, String sender, String login, String hostname) {}
onUserEnterChannel

2017-08-14 19:07 UTC, doppioandante commented on src/main/java/com/neroreflex/pizza/Trancio.java
> +        if (type == EventType.UserRequest) {
Non mi ricordo più se esiste lo switch in Java, ma qui si potrebbe usare.

2017-08-14 19:07 UTC, doppioandante commented on src/main/java/com/neroreflex/plugins/Convert.java
> +        String[] params = msg.split("([\\s]+)");
Penso sia giusto che il plugin si splitti il messaggio se ne ha bisogno, non è compito del bot quindi toglierei il commento.
Piuttosto non capisco il for dopo,  siccome splitti su \s+ in teoria tutti gli spazi multipli dovrebbero andarsene per cui params[i].length è sempre > 0. Forse devi togliere le parentesi tonde?
A quel punto basterebbe basterebbe fare
```
Vector<String> args = Arrays.asList(msg.split("\\s+"));
```

2017-08-14 19:07 UTC, doppioandante commented on src/main/java/com/neroreflex/plugins/Join.java
> +            if (params[i].length() > 0) args.add(params[i]);
idem come sopra

2017-08-14 19:07 UTC, doppioandante commented on src/main/java/com/neroreflex/plugins/LoadStore.java
> +            if (params[i].length() > 0) args.add(params[i]);
idem come sopra

2017-08-14 19:07 UTC, doppioandante commented on src/main/java/com/neroreflex/plugins/Time.java
> +            if (params[i].length() > 0) args.add(params[i]);
Idem come sopra

2017-08-14 19:07 UTC, doppioandante commented on src/main/java/com/neroreflex/plugins/UserCounter.java
> +    static String apiEndpoint = "";
Ecco questo non potrà essere static perché l'endpoint è privato. Propongo una variabile d'ambiente così la passiamo esternamente senza problemi ed è il metodo più semplice.

2017-08-14 19:07 UTC, doppioandante commented on src/main/java/com/neroreflex/pizza/Event.java
> +public class Event {
Secondo me visto che alla fine basta EventType + array di String per rappresentare un evento, conviene avere una classe Event che ha solo questi, ma non servono le sottoclassi.
Cambierei il costruttore in `public Event(EventType type, String... args)` e togliere EventType.Unknown

2017-08-14 19:07 UTC, doppioandante commented on src/main/java/com/neroreflex/pizza/Pizza.java
> +            } else if (command.compareTo("help") == 0) {
usa equals

2017-08-14 19:07 UTC, doppioandante commented on src/main/java/com/neroreflex/pizza/Pizza.java
> +            } else if (command.compareTo("info") == 0) {
usa equals

2017-08-15 15:12 UTC, NeroReflex commented on Documentazione/docs/plugin.md
> +  - protected void onShutdown(...): metodo chiamato nel main thread, al momento della attivazione del plugin, quindi _*PERICOLOSO*_
Una divisione per zero blocca l'intero bot, non solo il thread

2017-08-15 15:13 UTC, NeroReflex commented on src/main/java/com/neroreflex/pizza/Trancio.java
> +     * Se unqueueEvent ed enqueueEvent dovessero essere entrambi synchronized
Che c'è che non va? Ho scritto dovessero.

2017-08-15 15:26 UTC, doppioandante commented on src/main/java/com/neroreflex/pizza/Trancio.java
> +     * Se unqueueEvent ed enqueueEvent dovessero essere entrambi synchronized
Ero convinto di aver letto dovrebbero, devo mettere gli occhiali

2017-08-15 18:50 UTC, NeroReflex commented on src/main/java/com/neroreflex/pizza/Trancio.java
> +        if (type == EventType.UserRequest) {
Lo switch in java esiste, ma i case non possono contenere le label di una enum.

Questo significa che (nella enum) UserRequest = 0;
e nella switch case 0: ..... break;
è valido, ma
case EventType.UserRequest non lo e'.

2017-08-15 18:59 UTC, NeroReflex commented on src/main/java/com/neroreflex/pizza/Pizza.java
> + * La classe che, una volta istanziata identifichera' un bot connesso ad un server
Perchè sono stupido e non ci ho pensato abbastanza.
Avevo visto mkdocs fallire perchè avevo lasciato un accento sulla documentazione, e senza pensarci li ho tolti tutti.

2017-08-15 20:29 UTC, NeroReflex commented on Documentazione/docs/plugin.md
> +  - protected void onShutdown(...): metodo chiamato nel main thread, al momento della attivazione del plugin, quindi _*PERICOLOSO*_
Beh la divisione per zero era un esempio... Una eccezione non gestita causa il blocco del thread... Ma quelle funzioni sono eseguite sul thread principale...

2017-08-16 09:58 UTC, doppioandante reviewed
Ora mi piace molto di più, c'è ancora qualche cosa qua e là da sistemare.

2017-08-16 09:58 UTC, doppioandante commented on Documentazione/docs/plugin.md
> +  - protected void onShutdown(...): metodo chiamato nel main thread, al momento della attivazione del plugin, quindi _*PERICOLOSO*_
SI potrebbero fare eseguire sul thread del plugin, ma per ora lasciamo così.

2017-08-16 09:58 UTC, doppioandante commented on src/main/java/com/neroreflex/pizza/Pizza.java
> +        args.removeIf(i -> i.equals(""));
i -> i.isEmpty();
Alla fine si è capito come ci finiscono le stringhe vuote? accade solo nel caso in cui la stringa sia vuota?

2017-08-16 09:58 UTC, doppioandante commented on src/main/java/com/neroreflex/plugins/Time.java
> +        args.removeIf(i -> i.equals(""));
i -> i.isEmpty()

2017-08-16 09:58 UTC, doppioandante commented on src/main/java/com/neroreflex/plugins/HackerNews.java
> +                if (params[i].length() > 0) args.add(params[i]);
Metti lo stesso codice che hai usato altrove.

2017-08-16 09:58 UTC, doppioandante commented on src/main/java/com/neroreflex/plugins/Convert.java
> +        args.removeIf(i -> i.equals(""));
i -> i.isEmpty()

2017-08-16 09:58 UTC, doppioandante commented on src/main/java/com/neroreflex/pizza/Trancio.java
> +        if (type == EventType.UserRequest) {
Sulla [documentazione di oracle](https://docs.oracle.com/javase/tutorial/java/javaOO/enum.html) c'è scritto che lo switch si può usare con le enum

2017-08-16 09:58 UTC, doppioandante commented on src/main/java/com/neroreflex/plugins/PTforum.java
> +            joinedChannels.copyInto(channels);
Il foreach si può usare su tutte le collection iterabili mi pare, quindi non serve che copi joinedChannels in un array (mi era sfuggito nella prima review).

2017-08-16 13:56 UTC, doppioandante approved these changes

2017-08-16 14:07 UTC, closed without merging